steps:
  # Step 1: Download the service account key from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json
        
  # Step 2: Terraform Initialization
  - name: gcr.io/cloud-builders/terraform
    args: ["init"]
    
  # Step 3: Terraform Apply
  - name: gcr.io/cloud-builders/terraform
    args: ["apply", "-auto-approve"]
    env:
      - "TF_VAR_project_id=$_PROJECT_ID"
      - "TF_VAR_region=$_REGION"
      - "TF_VAR_bucket_name=$_BUCKET_NAME"

options:
  logging: "CLOUD_LOGGING_ONLY"

serviceAccount: "648323935885-compute@developer.gserviceaccount.com"

substitutions:
  _PROJECT_ID: "costco-udp"
  _REGION: "us-central1"
  _BUCKET_NAME: "gs://service_for_all/"
