steps:
  # Step 1: Download the service account key from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json
        
  # Disabled Bucket Logs.
  - name: gcr.io/cloud-builders/terraform
    args: ["apply", "-auto-approve"]

options:
  logging: "CLOUD_LOGGING_ONLY"
serviceAccount: "648323935885-compute@developer.gserviceaccount.com"


  # Step 2: Terraform Actions.      
  - name: gcr.io/cloud-builders/terraform
    args: ["init"]
  - name: gcr.io/cloud-builders/terraform
    args: ["apply", "-auto-approve"]
    env:
      - "TF_VAR_project_id=$PROJECT_ID"
      - "TF_VAR_region=$REGION"
      - "TF_VAR_bucket_name=$BUCKET_NAME"

substitutions:
  _PROJECT_ID: "costco-udp"
  _REGION: "us-central1"
  _BUCKET_NAME: "gs://service_for_all/"
