# steps:
#   # Step 1: Build the Docker image
#   - name: 'us-central1-docker.pkg.dev/costco-udp/costo-udp'
#     args:
#       - 'build'
#       - '-t'
#       - 'us-central1-docker.pkg.dev/costo-udp/costo-udp/costo-udp-image:latest'
#       - 'costco-udp-bigquery'  # Tag for your Docker image
#       - '.'  # Context is the current directory

#   # Step 2: Run the Docker container
#   - name: 'us-central1-docker.pkg.dev/costco-udp/costo-udp'
#     args:
#       - 'run'
#       - '--rm'
#       - '-v'
#       - '/path/to/your/service-account.json:/key.json'  # Mount the service account key
#       - '-e'
#       - 'GOOGLE_APPLICATION_CREDENTIALS=/key.json'
#       - 'us-central1-docker.pkg.dev/costo-udp/costo-udp/costo-udp-image:latest'
#       - 'costco-udp-bigquery'  # Name of the Docker image to run

# # Optional: Specify logs bucket
# logsBucket: gs://costco-udp-bigquery-logs
#--------------------------------------------------------------------------------------------------------------------------------------------




steps:
  # Step 1: Download the service account key from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/costco-udp/costo-udp/costo-udp-image:latest'
      - '.'

  # Step 3: Authenticate and run the Docker container with BigQuery access
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace/key.json:/key.json'  # Mount the key file inside the container
      - '-e'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/key.json'
      - 'us-central1-docker.pkg.dev/costco-udp/costo-udp/costo-udp-image:latest'
      - 'bash'
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=/key.json && \
        bq query --project_id=costco-udp --use_legacy_sql=false < scripts/create_table_and_insert.sql
# Optional: Specify logs bucket
logsBucket: gs://costco-udp-bigquery-logs
