steps:
  # Step 1: Download the service account key
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json

  # Step 2: Build Docker image with the context
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'
      - '.'

  # Step 3: Run Terraform commands in the container
  - name: 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        terraform init &&
        terraform apply -auto-approve
    dir: "/workspace"

# Specify substitutions and service account
substitutions:
  _PROJECT_ID: "costco-udp"
  _REGION: "us-central1"
  _BUCKET_NAME: "service_for_all"

serviceAccount: "648323935885-compute@developer.gserviceaccount.com"

# Include all files in the workspace for the build context
artifacts:
  objects:
    location: gs://<YOUR-BUCKET-NAME>/artifacts/
    paths:
      - '**'

substitutions:
  _PROJECT_ID: "costco-udp"
  _REGION: "us-central1"
  _BUCKET_NAME: "gs://service_for_all/"
