steps:
  # Step 1: Set up Google Cloud authentication
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project ${_PROJECT_ID}
        gcloud auth application-default login

  # Step 2: Set up Terraform
  - name: 'hashicorp/terraform:latest'
    args:
      - 'init'
      - '-input=false'

  # Step 3: Run Terraform Plan
  - name: 'hashicorp/terraform:latest'
    args:
      - 'plan'
      - '-var=project_id=${_PROJECT_ID}'
      - '-var=service_account_email=${_SERVICE_ACCOUNT_EMAIL}'
      - '-out=tfplan'

  # Step 4: Run Terraform Apply
  - name: 'hashicorp/terraform:latest'
    args:
      - 'apply'
      - '-input=false'
      - 'tfplan'

substitutions:
  _PROJECT_ID: "costco-udp"
  _SERVICE_ACCOUNT_EMAIL: "your-service-account-email"

# Optional: Control build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_SMALL'
