steps:
- name: 'gcr.io/costco-udp/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    bq query --use_legacy_sql=false < scripts/create_tables.sql

- name: 'gcr.io/costco-udp/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    bq query --use_legacy_sql=false < scripts/insert_data.sql

options:
  logs_bucket: gs://costco-udp-bigquery-logs
