logsBucket: gs://costco-udp-bigquery-logs
steps:
  - name: 'gcr.io/cloud-builders/bq'  # Use the official Google Cloud Build bq image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        bq query --use_legacy_sql=false < scripts/create_tables.sql

  - name: 'gcr.io/cloud-builders/bq'  # Reusing the bq image for the second step
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        bq query --use_legacy_sql=false < scripts/insert_data.sql
