logsBucket: gs://costco-udp-bigquery-logs
steps:
  - name: 'us-central1-docker.pkg.dev/costco-udp/costo-udp:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        bq query --use_legacy_sql=false < scripts/create_tables.sql

  - name: 'us-central1-docker.pkg.dev/costco-udp/costo-udp:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        bq query --use_legacy_sql=false < scripts/insert_data.sql
