steps:
  # Step 1: Download the service account key
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'
      - '.'
  - name: 'hashicorp/terraform:latest'
  args:
    - 'import'
    - 'google_storage_bucket.bucket'
    - '${_BUCKET_NAME}'  # Use your bucket name as a substitution variable


  # Step 3: Run Terraform
  - name: 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        tree /workspace &&
        terraform init &&
        terraform validate &&
        terraform apply -auto-approve
    dir: "/workspace"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: "costco-udp"
  _REGION: "us-central1"
  _BUCKET_NAME: "service_for_all"

serviceAccount: "648323935885-compute@developer.gserviceaccount.com"

artifacts:
  objects:
    location: gs://service_for_all/artifacts/
    paths:
      - '**'
