steps:
  # Step 1: Download the service account key from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json

  # Step 2: Build the Docker image from the current directory (.)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'
      - '.'  # This refers to the current directory as the build context

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'

  # Step 4: Terraform Initialization
  - name: 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'
    args: ["init"]
    
  # Step 5: Terraform Apply
  - name: 'us-central1-docker.pkg.dev/costco-udp/terraform-images/terraform:latest'
    args: ["apply", "-auto-approve"]
    env:
      - "TF_VAR_project_id=$_PROJECT_ID"
      - "TF_VAR_region=$_REGION"
      - "TF_VAR_bucket_name=$_BUCKET_NAME"

options:
  logging: "CLOUD_LOGGING_ONLY"

serviceAccount: "648323935885-compute@developer.gserviceaccount.com"

substitutions:
  _PROJECT_ID: "costco-udp"
  _REGION: "us-central1"
  _BUCKET_NAME: "gs://service_for_all/"
