# Deployment
steps:
  # Step 1: Download the service account key from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json
        
  # Step 2: Set up Google Cloud authentication
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       gcloud config set project ${_PROJECT_ID}
  #       gcloud auth application-default login
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/costco-udp/costo-udp/costo-udp-image:latest'
      - '.'

  # Step 3: Set up Terraform
  - name: 'hashicorp/terraform:latest'
    args:
      - 'init'
      - '-input=false'

  # Step 4: Run Terraform Plan
  - name: 'hashicorp/terraform:latest'
    args:
      - 'plan'
      - '-var=project_id=${_PROJECT_ID}'
      - '-var=service_account_email=${_SERVICE_ACCOUNT_EMAIL}'
      - '-var=topic_name=${_TOPIC_NAME}'
      - '-out=tfplan'

  # Step 5: Run Terraform Apply
  - name: 'hashicorp/terraform:latest'
    args:
      - 'apply'
      - '-input=false'
      - 'tfplan'

substitutions:
  _PROJECT_ID: "costco-udp"
  _SERVICE_ACCOUNT_EMAIL: "648323935885-compute@developer.gserviceaccount.com"
  _TOPIC_NAME: "my-topic"  # Add this if topic_name is a variable

# Specify a valid machine type
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
