steps:
  # Step to create the dataset and table, and insert records
  - name: 'gcr.io/cloud-builders/bq'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Run SQL commands from the script to create table and insert data
        bq query --use_legacy_sql=false < Costco_UDP/scripts/create_table_and_insert.sql

# Optional: Specify logs bucket
# logsBucket: gs://your-log-bucket
