# Deployment
steps:
  # Step 1: Download the service account key from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://costco-upd-json-key/costco-udp-dac031daa2fc.json /workspace/key.json
        
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/costco-udp/costo-udp/costo-udp-image:latest'
      - '.'

  # Step 3: Set up Terraform
  - name: 'hashicorp/terraform:latest'
    args:
      - 'init'
      - '-input=false'

  # Step 4: Run Terraform Plan
  - name: 'hashicorp/terraform:latest'
    args:
      - 'plan'
      - '-var=project_id=${_PROJECT_ID}'
      - '-var=service_account_email=${_SERVICE_ACCOUNT_EMAIL}'
      - '-var=topic_name=${_TOPIC_NAME}'
      - '-out=tfplan'

  # Step 5: Run Terraform Apply
  - name: 'hashicorp/terraform:latest'
    args:
      - 'apply'
      - '-input=false'
      - 'tfplan'

  # Step 6: Render the cloud bucket template.
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|\${bucket_name}|${_BUCKET_NAME}|g" /workspace/templates/bucket.tf.tpl
        sed -i "s|\${location}|${_LOCATION}|g" /workspace/templates/bucket.tf.tpl
        sed -i "s|\${storage_class}|${_STORAGE_CLASS}|g" /workspace/templates/bucket.tf.tpl
        sed -i "s|\${force_destroy}|${_FORCE_DESTROY}|g" /workspace/templates/bucket.tf.tpl

  # Step 7: Terraform Plan (Bucket)
  - name: 'hashicorp/terraform:latest'
    args:
      - 'plan'
      - '-var="bucket_name=${_BUCKET_NAME}"'
      - '-var="location=${_LOCATION}"'
      - '-var="storage_class=${_STORAGE_CLASS}"'
      - '-var="force_destroy=${_FORCE_DESTROY}"'
      - '-out=bucket-tfplan'

  # Step 8: Terraform Apply (Bucket)
  - name: 'hashicorp/terraform:latest'
    args:
      - 'apply'
      - '-input=false'
      - 'bucket-tfplan'

  - name: 'hashicorp/terraform:latest'
    args:
      - 'import'
      - 'google_storage_bucket.bucket'
      - '${_BUCKET_NAME}'


substitutions:
  _PROJECT_ID: "costco-udp"
  _SERVICE_ACCOUNT_EMAIL: "648323935885-compute@developer.gserviceaccount.com"
  _TOPIC_NAME: "pubsub--topic-one"  # Add this if topic_name is a variable
  _BUCKET_NAME: "upd-stg12370078008"
  _LOCATION: "us-central1"
  _STORAGE_CLASS: "STANDARD"
  _FORCE_DESTROY: "false"

# Specify a valid machine type
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
