name: Deploy Terraform to Create GCS Bucket

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/<GCP_PROJECT_ID>/locations/global/workloadIdentityPools/github-action-pool-udp-one/providers/github-provider
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan -var="gcp_project=${{ secrets.GCP_PROJECT_ID }}" -var="bucket_name=my-terraform-bucket-${{ github.run_id }}"

    - name: Apply Terraform
      run: terraform apply -auto-approve -var="gcp_project=${{ secrets.GCP_PROJECT_ID }}" -var="bucket_name=my-terraform-bucket-${{ github.run_id }}"
